Fix build warnings
AyatanaIndicators/ayatana-indicator-sound pull request #17
Opened 2021-03-09 23:24 UTC by tari01

About 100000 deprecations and other build nasties...

2021-03-18 06:47 UTC, khurshid-alam commented
@tari01 

When I enable tests some of the tests are failing. I am compiling on Ubuntu hirsute though.

2021-03-18 14:13 UTC, tari01 commented
> When I enable tests some of the tests are failing. I am compiling on Ubuntu hirsute though.

Yes, we still have https://github.com/AyatanaIndicators/ayatana-indicator-sound/issues/1. This is only about the warnings and the deprecated stuff.

2021-08-04 14:40 UTC, sunweaver requested changes
I left some comments, please resolve.

2021-08-04 14:40 UTC, sunweaver commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.16)
3.13? Please fix as a follow-up PR.

2021-08-04 14:40 UTC, sunweaver commented on src/accounts-service-access.vala
> +            accounts_proxy = yield new DBusProxy.for_bus (BusType.SYSTEM, DBusProxyFlags.DO_NOT_LOAD_PROPERTIES | DBusProxyFlags.DO_NOT_CONNECT_SIGNALS, null, "org.freedesktop.Accounts", "/org/freede
this shouldn't be in this commit

2021-08-04 14:40 UTC, sunweaver commented on src/accounts-service-access.vala
> +                _user_proxy = yield new DBusProxy.for_bus (BusType.SYSTEM, DBusProxyFlags.GET_INVALIDATED_PROPERTIES, null, "org.freedesktop.Accounts", user_path, "org.ayatana.AccountsService.Sound")
this shouldn't be in this commit

2021-08-04 14:40 UTC, sunweaver commented on src/volume-warning.vala
> - *
why remove these?

2021-08-04 20:54 UTC, sunweaver approved these changes
LGTM

2021-08-04 20:56 UTC, merged