Use CMAKE_INSTALL_FULL_*DIR locations for installation
AyatanaIndicators/ayatana-indicator-sound pull request #21
Opened 2021-08-03 22:52 UTC by tari01

2021-08-04 14:47 UTC, sunweaver requested changes
White space vs. non-white-space changes. Split them up into two commits.

2021-08-04 14:47 UTC, sunweaver commented on data/CMakeLists.txt
> +    DESTINATION "${DBUS_IFACE_DIR}"
Please separate white-space changes and content changes and split them up into two commits. Thanks.

2021-08-04 20:58 UTC, sunweaver approved these changes
ACK.

2021-08-04 21:02 UTC, sunweaver commented
I cannot simply rebase this branch due to conflicts with master, it seems. Please refurbish this PR: take latest master, cherry-pick changes of this PR on top, force-push to this PR's update branch.

2021-08-04 21:53 UTC, tari01 commented
> I cannot simply rebase this branch due to conflicts with master, it seems. Please refurbish this PR: take latest master, cherry-pick changes of this PR on top, force-push to this PR's update branch.

It should work - the changes it shows are the ones we want.

2021-08-05 06:00 UTC, sunweaver approved these changes
LGTM

2021-08-05 06:03 UTC, merged